#!/usr/bin/env python
# coding: utf-8
# This is for my Assignment for Applied Data Science Capstone Week 1. This will be mainly used for the capstone project.

# In[3]:


import pandas as pd
import numpy as np


# In[4]:


print("Hello Capstone Project Course!")


# In[ ]:



